INSERT INTO questao (id, caminho, titulo, pergunta) VALUES
(1, NULL, 'Briófitas', '_________ são plantas pequenas, geralmente com alguns poucos centímetros de altura, que vivem preferencialmente em locais úmidos e sombreados. '),
(2, NULL, 'Rizoides', 'Os ________ são filamentos que fixam a planta no ambiente em que ela vive.'),
(3, NULL, 'Anterozoides e OOsfera', 'As briófitas dependem da água para a reprodução sexuada. Nesta situação, os gametas masculinos (¬__________) se deslocam, com auxílio de seus flagelos, até os gametas femininos da planta (__________). Ao fecundar, o zigoto sofre mitose formando o embrião.'),
(4, NULL, 'Conhecimento sobre Pteridófitas', 'Uma garota estava observando a samambaia de sua mãe quando percebeu que todas as folhas estavam cheias de pontos escuros na face inferior. Achando que a planta em questão estava estragada, a menina arrancou todas as folhas da planta. De acordo com seus conhecimentos sobre pteridófitas, marque a alternativa que explica corretamente o que são os pontos pretos na folha.'),
(5, NULL, 'Musgos', 'Os musgos que crescem nos muros úmidos são:'),
(6, NULL, 'Plantas Vasculares', 'As __________ são plantas vasculares sem semente. '),
(7, NULL, 'Definição Rizoma-báculos', 'As pteridófitas possuem __________ tipo de caule semelhante a uma raiz, subterrâneo ou localizado bem próximo ao solo. Têm, ainda, folhas divididas em folíolos, sendo que as mais jovens são denominadas ___________, as quais se apresentam enroladas.'),
(8, NULL, 'Estrutura Pteridófita', 'As pteridófitas possuem uma estrutura denominada _________, que possui várias pequenas estruturas circulares chamadas________, responsáveis pelo processo de reprodução.'),
(9, NULL, 'Sobre Pteridófitas', 'As pteridófitas, por serem plantas vasculares possuem dois tipos de condução de água e sais minerais sendo eles o: _________ e o floema.'),
(10, NULL, 'UDESC', '(UDESC) O Reino Plantae é constituído por diferentes grupos de plantas, nos quais se encontram as Briófitas (filo/divisão Bryophyta) e as Pteridófitas (filo/divisão Pterophyta). A respeito dessas plantas, assinale a alternativa incorreta.');

INSERT INTO resposta (id, resposta, certa, id_pergunta) VALUES
(1, 'Pteridófitas', 0, 1),
(2, 'Angiospermas', 0, 1),
(3, 'Briófitas', 1, 1),
(4, 'Todas as três', 0, 1),
(5, 'Nenhuma das alternativas', 0, 1),
(6, 'Rizoides', 1, 2),
(7, 'Cauloide', 0, 2),
(8, 'Filoides', 0, 2),
(9, 'Todas as três', 0, 2),
(10, 'Nenhuma das alternativas', 0, 2),
(11, 'Espermatozoides e oosfera', 0, 3),
(12, 'Espermatozoide e ovócito', 0, 3),
(13, 'Anterozoides e oosfera', 1, 3),
(14, 'Anterozoides e ovócito', 0, 3),
(15, 'Nenhuma das alternativas', 0, 3),
(16, 'Os pontos escuros na face inferior da folha são os chamados báculos, estruturas reprodutoras.', 0, 4),
(17, 'Os pontos escuros na face inferior da folha são os chamados soros, estruturas que surgem em resposta a um ataque de fungos patogênicos.', 0, 4),
(18, 'Os pontos escuros na face inferior da folha são os chamados soros, estruturas onde são produzidos os esporos.', 1, 4),
(19, 'Os pontos escuros na face inferior da folha são os prótalos, a fase gametofítica da samambaia.', 0, 4),
(20, 'Os pontos escuros na face inferior da folha são os prótalos, a fase esporofítica da samambaia.', 0, 4),
(21, 'Esporófito de briófita.', 0, 5),
(22, 'Esporófito de Pteridófitas.', 0, 5),
(23, 'Associação de algas e Pteridófitas.', 0, 5),
(24, 'Gametófitos de briófitas', 1, 5),
(25, 'Associação de gametófitos de algas e pteridófitas', 0, 5),
(26, 'Angiospermas.', 0, 6),
(27, 'Briófitas', 0, 6),
(28, 'Pteridófitas', 1, 6),
(29, 'Todas as três', 0, 6),
(30, 'Nenhuma das alternativas', 0, 6),
(31, 'Rizoma-báculos', 1, 7),
(32, 'Coida-bainhas', 0, 7),
(33, 'Protalo-báculos', 0, 7),
(34, 'Todas as três', 0, 7),
(35, 'Nenhuma das alternativas', 0, 7),
(36, 'Esporófito-soros', 1, 8),
(37, 'Esporângio-sementes', 0, 8),
(38, 'Megafilos-folíolos', 0, 8),
(39, 'Todas as três', 0, 8),
(40, 'Nenhuma das alternativas', 0, 8),
(41, 'Meristema', 0, 9),
(42, 'Xilema', 1, 9),
(43, 'Rizoma', 0, 9),
(44, 'Todas as três', 0, 9),
(45, 'Nenhuma das alternativas', 0, 9),
(46, 'Na reprodução das Briófitas e Pteridófitas a meiose ocorre para formação de esporos.', 0, 10),
(47, 'Briófitas e Pteridófitas possuem um sistema eficiente de vasos condutores de seiva.', 1, 10),
(48, 'Briófitas e Pteridófitas dependem da água para a reprodução, pois seus gametas são flagelados.', 0, 10),
(49, 'Briófitas e Pteridófitas apresentam alternância de gerações, sendo as gerações duradouras as gametofíticas e esporofíticas, respectivamente.', 0, 10),
(50, 'Pteridófitas possuem raízes, caule e folhas verdadeiras, enquanto as Briófitas possuem rizoides, cauloides e filoides.', 0, 10);

INSERT INTO usuario (id, username, nome, email, senha, tipo) VALUES
(3, 'Jehymes', 'Jehymison Gil_Alves Oliveira', 'jehymes@gmail.com', '202CB962AC59075B964B07152D234B70', 0),
(4, 'admin', 'Jehymison Gil_Alves Oliveira', 'admin@admin.com', '21232F297A57A5A743894A0E4A801FC3', 1);
